### ISSUE TITLE
CI had been failing (for ubuntus?) for quite a while

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad-installer#166] opened 2023-06-16 13:07 UTC
according to emails seems to fail regularly since May 28.

**Comment by jwodder** [comment] 2023-06-16 13:40
@yarikoptic Part of the problem is addressed by #167, but the tests have been failing on Ubuntu for all Pythons since June 11 due to conda for some reason installing datalad v0.9.3 (which fails when called with `--help`) instead of the latest version.  Take a look at the conda output in the logs and see if you can figure out why.

**Comment by jwodder** [comment] 2023-06-19 12:54
@yarikoptic Should this upgrade only be done if also running on Linux?  Because the tests are currently passing on macOS and Windows.

**Comment by yarikoptic** [comment] 2023-06-19 13:35
Based on that empirical observation, let's indeed do just on Linux. Please add a comment describing the situation

**Closed** 2023-06-19 15:56 UTC
